name = "ream"
version = "0.1.0"
description = "REAM is an event sourcing system"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.

licences = ["Apache-2.0"]
repository = { type = "github", user = "altenwald", repo = "ream" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.30"
gleam_otp = "~> 0.5"
hug = "~> 0.1"
gloml = "~> 0.1"
gleam_erlang = "~> 0.19"
birl = "~> 0.14"
nibble = "~> 1.0.0-rc.3"

[dev-dependencies]
glacier = "~> 0.9"

[documentation]
pages = [
    { title = "LICENSE", path = "license.html", source = "LICENSE" },
    { title = "Protocol", path = "protocol.html", source = "docs/protocol.md" },
    { title = "Storage", path = "storage.html", source = "docs/storage.md" }
]
